version: 2
enable-beta-ecosystems: true

registries:
  nav-ghpr:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 20
    registries: "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:05"
      timezone: "Europe/Oslo"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
